macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

check_task:
  install_script: brew install nodejs
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  test_script: npm test
  binaries_artifacts:
    path: "node_modules/duckdb/lib/binding/duckdb.node"
