windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019

  env:
    PATH: C:\Python311:${PATH}

  python_install_script: choco install -y python3
  pip_upgrade_script: python.exe -m pip install -U pip
  pip_install_script: pip install duckdb pyarrow multithread[progress] github-action-utils
  test_script: python windows.py

check_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  install_script: brew install nodejs
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  test_script: npm test
  binaries_artifacts:
    path: "node_modules/duckdb/lib/binding/duckdb.node"
