# windows_task:
#   windows_container:
#     image: cirrusci/windowsservercore:2019

#   env:
#     PATH: C:\Python311;${PATH}

#   python_install_script: choco install -y python3 visualstudio2019-workload-vctools
#   pip_cache:
#     folder: ~\AppData\Local\pip\cache
#     populate_script: python.exe -m pip install duckdb pyarrow multithread[progress] certifi pip_system_certs github-action-utils -U
#   test_script: python.exe windows.py

check_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  env:
    PATH: /Users/admin/.nvm/versions/node/v16.13.2/bin:${PATH}

  install_script: |
    brew install nvm

    mkdir ~/.nvm

    export NVM_DIR="$HOME/.nvm"
    [ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && . "$(brew --prefix)/opt/nvm/nvm.sh" # This loads nvm
    [ -s "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" ] && . "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion

    nvm install 16.13.2

    nvm use 16.13.2

    which node

  version_script: |
    node -v
    npm -v
  node_modules_cache:
    folder: node_modules
    fingerprint_script: |
      cat package-lock.json
      node -v
    populate_script: npm install duckdb
  test_script: npm test
  binaries_artifacts:
    path: "node_modules/duckdb/lib/binding/duckdb.node"
