on: push

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - run: wget 'https://drive.google.com/uc?export=download&id=18gv0Yd_a-Zc7CSolol8qeYVAAzSthnSN&confirm=t'
      - run: python3 -m pip install duckdb pyarrow 
      - run: python3 windows.py
